server:
  port: 9021

spring:
  application:
    name: zt-timer
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bitstorm-svr?serverTimezone=GMT%2B8&characterEncoding=utf8&&allowMultiQueries=true&useSSL=false
    username: root
    password: 1234
  data:
    redis:
      host: 120.55.13.0
      port: 6379
      password: 123456
      database: 3
      jedis:
        pool:
          max-active: 8 #?????

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl